(function() {var implementors = {};
implementors["twitch_client"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html\" title=\"struct std::time::duration::Duration\">Duration</a>","impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;&amp;'b <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>&gt; for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>","impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;&amp;'b <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>&gt; for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>","impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;&amp;'b <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>&gt; for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl&lt;'a, 'b&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;&amp;'b <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>&gt; for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9.11/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Div.html\" title=\"trait core::ops::Div\">Div</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i32.html\">i32</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
